-- Geração de Modelo físico
-- SQL ANSI 2003 - brModelo corrigido

CREATE DATABASE ACADEMIA;
USE ACADEMIA;

-- Tabela de Instrutores
CREATE TABLE INSTRUTOR (
  ID_INSTRUTOR INT AUTO_INCREMENT PRIMARY KEY,
  EMAIL_INSTRUTOR VARCHAR(100),
  SENHA_INSTRUTOR VARCHAR(255),
  CPF_INSTRUTOR VARCHAR(14),
  TEL_INSTRUTOR VARCHAR(14),
  USUARIO_INSTRUTOR VARCHAR(80)
);

-- Tabela de Aulas
CREATE TABLE AULA (
  ID_AULA INT AUTO_INCREMENT PRIMARY KEY,
  DATA DATETIME,
  DESCRICAO VARCHAR(255)
);

-- Tabela de Administradores
CREATE TABLE ADMIN (
  ID_ADM INT AUTO_INCREMENT PRIMARY KEY,
  USUARIO_ADM VARCHAR(100),
  SENHA_ADM VARCHAR(255)
);

-- Tabela de Alunos
CREATE TABLE ALUNO (
  ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY,
  CPF_ALUNO VARCHAR(14),
  USUARIO_ALUNO VARCHAR(80),
  SENHA_HASH VARCHAR(255),
  EMAIL_ALUNO VARCHAR(100),
  TEL_ALUNO VARCHAR(14)
);

-- Tabela de Turmas
CREATE TABLE TURMA (
  ID_TURMA INT AUTO_INCREMENT PRIMARY KEY,
  NUM_ALUNOS INT,
  ID_INSTRUTOR INT,
  ID_AULA INT,
  FOREIGN KEY (ID_INSTRUTOR) REFERENCES INSTRUTOR(ID_INSTRUTOR),
  FOREIGN KEY (ID_AULA) REFERENCES AULA(ID_AULA)
);

-- Tabela intermediária PERTENCE (ALUNO x TURMA)
CREATE TABLE PERTENCE (
  ID_ALUNO INT,
  ID_TURMA INT,
  PRIMARY KEY (ID_ALUNO, ID_TURMA),
  FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(ID_ALUNO),
  FOREIGN KEY (ID_TURMA) REFERENCES TURMA(ID_TURMA)
);

-- Tabela de Agendamentos
CREATE TABLE AGENDAMENTO (
  ID_AGENDAMENTO INT AUTO_INCREMENT PRIMARY KEY,
  DATA_AGENDAMENTO DATETIME,
  TIPO_AULA VARCHAR(255),
  NOME_AULA VARCHAR(100),
  ID_AULA INT,
  ID_ALUNO INT,
  ID_TURMA INT,
  FOREIGN KEY (ID_AULA) REFERENCES AULA(ID_AULA),
  FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(ID_ALUNO),
  FOREIGN KEY (ID_TURMA) REFERENCES TURMA(ID_TURMA)
);
