-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE ALUNO+TURMA (
ID_ALUNO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
USUARIO_ALUNO VARCHAR(80),
CPF_ALUNO VARCHAR(14),
TEL_ALUNO VARCHAR(14),
SENHA_HASH VARCHAR(255),
EMAIL_ALUNO VARCHAR(100),
ID_TURMA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NUM_ALUNOS INT,
ID_INSTRUTOR INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
ID_AULA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
PRIMARY KEY(ID_ALUNO,ID_TURMA)
)

CREATE TABLE INSTRUTOR (
TEL_INSTRUTOR VARCHAR(14),
ID_INSTRUTOR INT PRIMARY KEY AUTO_INCREMENT NOT NULL PRIMARY KEY,
USUARIO_INSTRUTOR VARCHAR(80),
CPF_INSTRUTOR VARCHAR(14),
SENHA_INSTRUTOR VARCHAR(255),
EMAIL_INSTRUTOR VARCHAR(100)
)

CREATE TABLE AGENDAMENTO (
ID_AGENDAMENTO INT PRIMARY KEY AUTO_INCREMENT NOT NULL PRIMARY KEY,
DATA_AGENDAMENTO DATETIME,
NOME_AULA /*erro: ??*/,
TIPO_AULA VARCHAR(255),
ID_AULA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
ID_ALUNO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
ID_TURMA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
FOREIGN KEY(ID_TURMA,,) REFERENCES ALUNO+TURMA (ID_ALUNO,ID_TURMA)
)

CREATE TABLE AULA (
DATA DATETIME,
ID_AULA INT PRIMARY KEY AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOME_AULA VARCHAR(70),
DESCRICAO VARCHAR(255)
)

CREATE TABLE ADMIN (
ID_ADM INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
USUARIO_ADM VARCHAR(100),
SENHA_ADM VARCHAR(255)
)

ALTER TABLE ALUNO+TURMA ADD FOREIGN KEY(ID_INSTRUTOR) REFERENCES INSTRUTOR (ID_INSTRUTOR)
ALTER TABLE ALUNO+TURMA ADD FOREIGN KEY(ID_AULA) REFERENCES AULA (ID_AULA)
ALTER TABLE AGENDAMENTO ADD FOREIGN KEY(ID_AULA) REFERENCES AULA (ID_AULA)
